### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by cortner** [cortner/DerivativeTests.jl#1]
* [ ] Check out `https://git.tu-freiberg.de/ng/DerivativeTests.jl`
* [ ] discuss and clean up the entire logic of this package
* [ ] robust heuristic for choosing fd parameter `h`
* [ ] options for other fd operations
* [ ] should the finite differences be performed in higher precision to get more robust tests?
* [ ] use logging instead of `@printf`???
* [ ] extend to admit `StaticArrays` (or at least test this!)
* [ ] create a "report type"
* [ ] Implement testing via AD
* [x] unified code for scalar / vectorial functions
* [x] Write proper README / docs

**Comment by pkofod** [comment]
Great, thanks. I'll have a look and also try it out myself :)

**Comment by cortner** [comment]
the basic functionality is there I think. Main question before registering is (a) making sure the name of the package is ok; and (b) the name of the only currently exported function `fdtest` is ok. I'm not sure about the latter. 

But then again it can be quickly fixed with a deprecation cycle. Anyhow, one you tell you think it is ok, I'll have a go at registering it.

**Comment by cortner** [comment]
@pkofod Do you still think this package will be generally useful, or would it be best to just get rid of it again?

**Comment by pkofod** [comment]
I’m not sure. If you want to clean it up I understand that :)
